version: "2"
services:
    # MySQL 5.7: https://hub.docker.com/_/mysql/
    mysql:
        container_name: mysql
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_USER: "sd"
            MYSQL_PASSWORD: "sd"
            MYSQL_DATABASE: "sd"

    # Redis 3.2.10: https://hub.docker.com/_/redis/
    redis:
        container_name: redis
        image: redis:3.2.10

    # SD框架阿里云内网registry-internal.cn-hangzhou.aliyuncs.com/youwoxing/dev
    dev1:
        container_name: dev1
        image: registry.cn-hangzhou.aliyuncs.com/youwoxing/dev
        links:
            - mysql
            - redis
        ports:
            - "10001:8081"
            - "10022:22"